### PR TITLE
chore: [weapp-domains] UI update

### PR DESCRIPTION
**Pull request by myleslee**
ref #2370

### CODE REVIEW

**Comment by myleslee** [comment]
**Before**:
screen shot 2017-11-07 at 23 11 10

**After**:
screen shot 2017-11-07 at 23 10 39

**Before**:

screen shot 2017-11-07 at 23 45 37

**After**:
screen shot 2017-11-07 at 23 50 19

**Comment by myleslee** [comment]
不过看过了论坛的问题，我建议把文档中的步骤再调整一下，三步变两步：

**Before**:

screen shot 2017-11-08 at 00 52 41


**After**:

screen shot 2017-11-08 at 00 52 00

**Comment by leeyeh** [comment]
既然你改了，那这里的 bug 能否顺手修一下： https://github.com/leancloud/docs/pull/2371/files#diff-83ebfb679329048e8000852713f77427R100

qcloud 与 us 都没有 i = 1 的情况。

**Comment by myleslee** [comment]
@leeyeh 修了

**Pull request merged**
